const DB_NAME='farz-local-v1', STORE='files';
const state={dataset:[],referralFiles:[],results:[],filter:'all',query:''};
const $=id=>document.getElementById(id);
function normalize(value){return String(value??'').normalize('NFKC').replace(/[٠-٩]/g,d=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(d))).replace(/[۰-۹]/g,d=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(d))).replace(/[\u064B-\u065F\u0670\u0640]/g,'').replace(/[\s_\-–—/\\.,;:|!؟?()[\]{}<>"'`~@#$%^&*+=]/g,'').toLowerCase()}
function escape(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function plateKey(row){const key=Object.keys(row).find(k=>/لوح|plate|رقم.*سيار|vehicle.*no/i.test(k));return key||Object.keys(row)[0]}
function toast(msg,type='info'){const n=document.createElement('div');n.className='toast '+type;n.textContent=msg;$('toastContainer').append(n);setTimeout(()=>n.remove(),3500)}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function saveLocal(){const db=await openDB();const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(state.dataset,'dataset');tx.objectStore(STORE).put(state.results,'results');return new Promise(r=>tx.oncomplete=r)}
async function loadLocal(){try{const db=await openDB();const get=k=>new Promise(r=>{const q=db.transaction(STORE).objectStore(STORE).get(k);q.onsuccess=()=>r(q.result||[])});state.dataset=await get('dataset');state.results=await get('results');if(state.dataset.length)renderStats();if(state.results.length)renderResults()}catch(e){toast('تعذر فتح التخزين المحلي','error')}}
function parseFile(file){return new Promise((resolve,reject)=>{const ext=file.name.toLowerCase();if(ext.endsWith('.xlsx')||ext.endsWith('.xls')){const rd=new FileReader();rd.onload=e=>{try{const wb=XLSX.read(e.target.result,{type:'array'});const ws=wb.Sheets[wb.SheetNames[0]];resolve(XLSX.utils.sheet_to_json(ws,{defval:''}))}catch(x){reject(x)}};rd.readAsArrayBuffer(file)}else Papa.parse(file,{header:true,skipEmptyLines:true,worker:true,complete:r=>resolve(r.data),error:reject})})}
function renderStats(){const counts=new Map();state.dataset.forEach(r=>{const k=normalize(r[plateKey(r)]);if(k)counts.set(k,(counts.get(k)||0)+1)});$('statTotalRecords').textContent=state.dataset.length.toLocaleString();$('statDistinctPlates').textContent=counts.size.toLocaleString();$('statDuplicatePlates').textContent=[...counts.values()].filter(n=>n>1).length.toLocaleString();$('statLastUpdated').textContent=new Date().toLocaleDateString('ar');$('datasetStatusTag').textContent='✅ بيانات جاهزة';$('datasetStatusTag').className='status-tag active'}
async function handleDataset(file){$('datasetMessage').textContent='جاري القراءة والمعالجة محليًا...';$('datasetProgress').style.display='block';$('datasetProgressFill').style.width='30%';try{state.dataset=await parseFile(file);$('datasetProgressFill').style.width='100%';renderStats();await saveLocal();toast(`تم حفظ ${state.dataset.length.toLocaleString()} سيارة على جهازك`,'success');$('datasetMessage').textContent='تم الحفظ في المتصفح — لا تحتاج لرفع الملف مرة أخرى على هذا الجهاز.'}catch(e){toast('تعذر قراءة الملف: '+e.message,'error')}}
function rowText(r){return Object.values(r).join(' ')}
function match(){if(!state.dataset.length){toast('ارفع ملف بيانات السيارات أولًا','error');return}const started=performance.now(),map=new Map();state.dataset.forEach(r=>{const k=normalize(r[plateKey(r)]);if(k){if(!map.has(k))map.set(k,[]);map.get(k).push(r)}});const refs=[];state.referralFiles.forEach(x=>x.rows.forEach(r=>refs.push({...r,'ملف الإحالة':x.name})));const out=[];let matched=0;refs.forEach(ref=>{const key=normalize(ref[plateKey(ref)]);const cars=map.get(key)||[];if(cars.length){matched++;cars.forEach(car=>out.push({'حالة المطابقة':cars.length>1?'تطابق متعدد':'متطابق','اللوحة':car[plateKey(car)],'لوحة الإحالة':ref[plateKey(ref)],...car,...ref}))}else out.push({'حالة المطابقة':'غير متطابق',...ref})});state.results=out;state.filter='all';state.query='';$('sumTotalRef').textContent=refs.length.toLocaleString();$('sumMatchedRef').textContent=matched.toLocaleString();$('sumUnmatchedRef').textContent=(refs.length-matched).toLocaleString();$('sumTimeMs').textContent=Math.round(performance.now()-started)+' ms';$('resultsSection').hidden=false;saveLocal();renderResults();toast('اكتملت المطابقة محليًا','success')}
function visible(){return state.results.filter(r=>(state.filter==='all'||(state.filter==='matched'&&r['حالة المطابقة']==='متطابق')||(state.filter==='multiple'&&r['حالة المطابقة']==='تطابق متعدد'))&&(!state.query||rowText(r).toLowerCase().includes(state.query.toLowerCase())))}
function renderResults(){const rows=visible(),cols=[...new Set(rows.flatMap(Object.keys))];$('resultsTableHead').innerHTML='<tr>'+cols.map(c=>`<th>${escape(c)}</th>`).join('')+'</tr>';$('resultsTableBody').innerHTML=rows.slice(0,500).map(r=>'<tr>'+cols.map(c=>{const v=r[c];return c==='حالة المطابقة'?`<td><span class="badge ${v==='متطابق'?'badge-matched':v==='تطابق متعدد'?'badge-multiple':'badge-unmatched'}">${escape(v)}</span></td>`:`<td>${escape(v)}</td>`}).join('')+'</tr>').join('')||`<tr><td colspan="99">لا توجد نتائج</td></tr>`}
function download(format){const rows=visible();if(!rows.length)return toast('لا توجد نتائج للتصدير','error');let blob,name;if(format==='csv'){const csv='\ufeff'+Papa.unparse(rows);blob=new Blob([csv],{type:'text/csv;charset=utf-8'});name='نتائج-المطابقة.csv'}else{const ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'النتائج');XLSX.writeFile(wb,'نتائج-المطابقة.xlsx');return}const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
$('datasetFileInput').onchange=e=>e.target.files[0]&&handleDataset(e.target.files[0]);$('referralFileInput').onchange=async e=>{state.referralFiles=[];for(const f of e.target.files)state.referralFiles.push({name:f.name,rows:await parseFile(f)});$('referralFilesList').innerHTML=state.referralFiles.map(x=>`<span class="selected-file-chip">📄 ${escape(x.name)} (${x.rows.length})</span>`).join('');$('startMatchBtn').disabled=!state.referralFiles.length};$('startMatchBtn').onclick=match;$('quickSearchBtn').onclick=()=>{const q=normalize($('quickSearchInput').value),rows=state.dataset.filter(r=>normalize(r[plateKey(r)])===q);$('quickSearchResults').innerHTML=rows.length?rows.slice(0,20).map(r=>`<div class="card">${Object.entries(r).map(([k,v])=>`<b>${escape(k)}:</b> ${escape(v)} `).join('')}</div>`).join(''):'<p class="muted">لا توجد مطابقة</p>'};$('tableSearchInput').oninput=e=>{state.query=e.target.value;renderResults()};document.querySelectorAll('.tab-btn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.filter=b.dataset.filter;renderResults()});$('exportCsvBtn').onclick=()=>download('csv');$('exportXlsxBtn').onclick=()=>download('xlsx');loadLocal();
