const DB_NAME='farz-local-pro',STORE='files';
const state={dataset:[],referralFiles:[],results:[],filter:'all',query:''};
const $=id=>document.getElementById(id);
const normalize=v=>String(v??'').normalize('NFKC').replace(/[٠-٩]/g,d=>'٠١٢٣٤٥٦٧٨٩'.indexOf(d)).replace(/[۰-۹]/g,d=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(d)).replace(/[\u064B-\u065F\u0670\u0640]/g,'').replace(/[\s_\-–—/\\.,;:|!؟?()[\]{}<>"'`~@#$%^&*+=]/g,'').toLowerCase();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const plateKey=row=>Object.keys(row).find(k=>/لوح|plate|رقم.*سيار|vehicle.*no/i.test(k))||Object.keys(row)[0];
function toast(msg,type='info'){const n=document.createElement('div');n.className=`toast ${type}`;n.textContent=msg;$('toastContainer').append(n);setTimeout(()=>n.remove(),3600)}
function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>req.result.createObjectStore(STORE);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function store(key,value){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(value,key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
async function read(key){const db=await openDB();return new Promise(resolve=>{const req=db.transaction(STORE).objectStore(STORE).get(key);req.onsuccess=()=>resolve(req.result||[])})}
async function persist(){await Promise.all([store('dataset',state.dataset),store('results',state.results)])}
async function restore(){try{state.dataset=await read('dataset');state.results=await read('results');if(state.dataset.length)renderStats();if(state.results.length){$('resultsSection').hidden=false;renderResults()}}catch(e){toast('تعذر فتح التخزين المحلي','error')}}
function parseFile(file){return new Promise((resolve,reject)=>{const name=file.name.toLowerCase();if(name.endsWith('.xlsx')||name.endsWith('.xls')){const reader=new FileReader();reader.onload=e=>{try{const book=XLSX.read(e.target.result,{type:'array'});resolve(XLSX.utils.sheet_to_json(book.Sheets[book.SheetNames[0]],{defval:''}))}catch(err){reject(err)}};reader.readAsArrayBuffer(file)}else Papa.parse(file,{header:true,skipEmptyLines:true,worker:true,complete:r=>resolve(r.data),error:reject})})}
function renderStats(){const counts=new Map();state.dataset.forEach(r=>{const k=normalize(r[plateKey(r)]);if(k)counts.set(k,(counts.get(k)||0)+1)});$('statTotalRecords').textContent=state.dataset.length.toLocaleString();$('statDistinctPlates').textContent=counts.size.toLocaleString();$('statDuplicatePlates').textContent=[...counts.values()].filter(v=>v>1).length.toLocaleString();$('statLastUpdated').textContent=new Date().toLocaleDateString('ar-EG');$('datasetStatusTag').textContent='● بيانات جاهزة';$('datasetStatusTag').className='status-tag active'}
async function importDataset(file){$('datasetMessage').textContent='جاري قراءة الملف ومعالجته على جهازك...';$('datasetProgress').hidden=false;$('datasetProgressFill').style.width='25%';try{state.dataset=await parseFile(file);$('datasetProgressFill').style.width='100%';renderStats();await store('dataset',state.dataset);toast(`تم حفظ ${state.dataset.length.toLocaleString()} سيارة بنجاح`,'success');$('datasetMessage').textContent='تم الحفظ محليًا — يمكنك إغلاق الصفحة والعودة لاحقًا.';setTimeout(()=>$('datasetProgress').hidden=true,900)}catch(e){toast('فشل قراءة الملف: '+e.message,'error');$('datasetProgress').hidden=true}}
function activateDropzone(zone,input,handler){['dragenter','dragover'].forEach(ev=>zone.addEventListener(ev,e=>{e.preventDefault();zone.classList.add('dragging')}));['dragleave','drop'].forEach(ev=>zone.addEventListener(ev,e=>{e.preventDefault();zone.classList.remove('dragging')}));zone.addEventListener('drop',e=>{if(e.dataTransfer.files.length)handler([...e.dataTransfer.files])});input.addEventListener('change',()=>{if(input.files.length)handler([...input.files]);input.value=''})}
function rowText(row){return Object.values(row).join(' ').toLowerCase()}
function runMatch(){if(!state.dataset.length)return toast('ارفع قاعدة بيانات السيارات أولًا','error');const started=performance.now(),index=new Map();state.dataset.forEach(car=>{const key=normalize(car[plateKey(car)]);if(key){if(!index.has(key))index.set(key,[]);index.get(key).push(car)}});const refs=state.referralFiles.flatMap(file=>file.rows.map(row=>({...row,'ملف الإحالة':file.name})));let matched=0;const result=[];refs.forEach(ref=>{const cars=index.get(normalize(ref[plateKey(ref)]))||[];if(cars.length){matched++;cars.forEach(car=>result.push({'حالة المطابقة':cars.length>1?'تطابق متعدد':'متطابق','اللوحة':car[plateKey(car)],'لوحة الإحالة':ref[plateKey(ref)],...car,...ref}))}else result.push({'حالة المطابقة':'غير متطابق',...ref})});state.results=result;state.filter='all';state.query='';$('sumTotalRef').textContent=refs.length.toLocaleString();$('sumMatchedRef').textContent=matched.toLocaleString();$('sumUnmatchedRef').textContent=(refs.length-matched).toLocaleString();$('sumTimeMs').textContent=`${Math.round(performance.now()-started)} ms`;$('resultsSection').hidden=false;renderResults();persist();$('resultsSection').scrollIntoView({behavior:'smooth',block:'start'});toast('اكتملت المطابقة محليًا','success')}
function visible(){return state.results.filter(row=>(state.filter==='all'||state.filter==='matched'&&row['حالة المطابقة']==='متطابق'||state.filter==='multiple'&&row['حالة المطابقة']==='تطابق متعدد')&&(!state.query||rowText(row).includes(state.query.toLowerCase())))}
function renderResults(){const rows=visible(),cols=[...new Set(rows.flatMap(Object.keys))];$('resultsCount').textContent=`${rows.length.toLocaleString()} نتيجة`;$('resultsTableHead').innerHTML=`<tr>${cols.map(c=>`<th>${esc(c)}</th>`).join('')}</tr>`;$('resultsTableBody').innerHTML=rows.slice(0,500).map(row=>`<tr>${cols.map(c=>{const val=row[c]??'';if(c==='حالة المطابقة'){const cls=val==='متطابق'?'badge-matched':val==='تطابق متعدد'?'badge-multiple':'badge-unmatched';return `<td><span class="badge ${cls}">${esc(val)}</span></td>`}return `<td>${esc(val)||'<span class="muted">—</span>'}</td>`}).join('')}</tr>`).join('')||`<tr><td colspan="99" style="text-align:center;padding:30px;color:var(--muted)">لا توجد نتائج مطابقة</td></tr>`}
function quickSearch(){const query=normalize($('quickSearchInput').value);if(!query)return toast('اكتب رقم اللوحة أولًا','error');const rows=state.dataset.filter(row=>normalize(row[plateKey(row)])===query);$('quickSearchResults').innerHTML=rows.length?rows.slice(0,20).map(row=>`<div class="result-mini">${Object.entries(row).map(([k,v])=>`<span><b>${esc(k)}:</b> ${esc(v)||'—'}</span>`).join(' · ')}</div>`).join(''):'<div class="empty-state"><span>×</span><p>لا توجد سيارة بهذه اللوحة</p></div>'}
function download(format){const rows=visible();if(!rows.length)return toast('لا توجد نتائج للتصدير','error');if(format==='xlsx'){const ws=XLSX.utils.json_to_sheet(rows),book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,ws,'نتائج المطابقة');XLSX.writeFile(book,'نتائج-المطابقة.xlsx');return}const blob=new Blob(['\ufeff'+Papa.unparse(rows)],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='نتائج-المطابقة.csv';a.click();URL.revokeObjectURL(a.href)}
activateDropzone($('datasetDropzone'),$('datasetFileInput'),files=>importDataset(files[0]));activateDropzone($('referralDropzone'),$('referralFileInput'),async files=>{state.referralFiles=[];for(const file of files)state.referralFiles.push({name:file.name,rows:await parseFile(file)});$('referralFilesList').innerHTML=state.referralFiles.map(f=>`<span class="file-chip">📄 ${esc(f.name)} <small>${f.rows.length.toLocaleString()} صف</small></span>`).join('');$('startMatchBtn').disabled=!state.referralFiles.length});$('quickSearchBtn').onclick=quickSearch;$('quickSearchInput').onkeydown=e=>{if(e.key==='Enter')quickSearch()};$('startMatchBtn').onclick=runMatch;$('tableSearchInput').oninput=e=>{state.query=e.target.value;renderResults()};document.querySelectorAll('.tab-btn').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.tab-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');state.filter=btn.dataset.filter;renderResults()});$('exportCsvBtn').onclick=()=>download('csv');$('exportXlsxBtn').onclick=()=>download('xlsx');$('themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('farz-theme',document.body.classList.contains('dark')?'dark':'light');$('themeBtn').textContent=document.body.classList.contains('dark')?'☀':'☾'};$('clearAllBtn').onclick=async()=>{if(confirm('هل تريد مسح جميع البيانات المحفوظة من هذا الجهاز؟')){state.dataset=[];state.results=[];state.referralFiles=[];await Promise.all([store('dataset',[]),store('results',[])]);location.reload()}};if(localStorage.getItem('farz-theme')==='dark'){$('themeBtn').click()}restore();
